### ISSUE TITLE
"JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Index: -1, Size: 0

### ISSUE THREAD

**Issue by bekor** [CodecoolBP20171/java-se-snake-uptown-funktion#32]
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Index: -1, Size: 0
	at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:661)
	at java.util.ArrayList.add(ArrayList.java:473)
	at com.sun.javafx.collections.ObservableListWrapper.doAdd(ObservableListWrapper.java:101)
	at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:151)
	at com.sun.javafx.collections.VetoableListDecorator.add(VetoableListDecorator.java:320)
	at com.codecool.snake.entities.snakes.SnakeBody.<init>(SnakeBody.java:31)
	at com.codecool.snake.entities.snakes.SnakeHead.addPart(SnakeHead.java:89)
	at com.codecool.snake.entities.powerups.SimplePowerup.apply(SimplePowerup.java:26)
	at com.codecool.snake.entities.snakes.SnakeHead.step(SnakeHead.java:73)
	at com.codecool.snake.GameLoop.handle(GameLoop.java:20)
	at javafx.animation.AnimationTimer$AnimationTimerReceiver.lambda$handle$484(AnimationTimer.java:57)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.animation.AnimationTimer$AnimationTimerReceiver.handle(AnimationTimer.java:56)
	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:357)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:506)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:748)

**Comment by bencef** [comment]
probably a race condition :)
